rust-lang/a-mir-formality

.github/workflows/ci.yaml
This enables Github Actions on this repo. Redex somehow relies on gtk properly initialized on linux, so `xvfb` is used to provide a temporary x-server during the execution.
It also complains that `grammar.rkt` is missing but i guess that's `mir/grammar.rkt` so i just fixed it.
=> Run tests on CI.

book/src/closer-look-decl.md, book/src/closer-look-ty.md, src/decl/grammar.rkt, src/logic/grammar.rkt, src/ty/grammar.rkt
These anchors should help us keep the book and code in sync, especially since we are hoping to develop the model and the book simultaneously.
Note: one tradeoff when using these anchors is that we can't cleanup up the code for presentation in the docs (by removing comments, or "snipping" pieces of code).
=> Replace some code snippets with anchors

src/decl/test/copy.rkt
we were using the env from the wrong crate!
=> fix copy test

book/src/closer-look-decl.md, docs/blog/2022-05-12.mdx, docs/docs/how-formality-works/closer-look-decl.md, docs/docs/setup.md, src/decl/decl-ok.rkt, src/decl/test/basic-consts.rkt, src/decl/test/coinductive/issue-43784.rkt, src/decl/test/coinductive/magic-issue-xxx.rkt, src/decl/test/drop.rkt, src/decl/test/multi-crate.rkt, src/decl/test/supertraits.rkt, src/logic/elaborate.rkt, src/ty/grammar.rkt, src/ty/parameters.rkt, src/ty/test/test-alias-subtyping.rkt, src/ty/test/test-outlives.rkt, src/ty/test/test-subtyping.rkt, src/ty/where-clauses.rkt, test
Change the syntax of where-clauses to be more Rust-like, also detecting a bunch of places we failed to do the `where-clause->goal` transformation.
=> Rusty where clauses

book/src/closer-look-decl.md, book/src/closer-look-ty.md, docs/docs/how-formality-works/closer-look-decl.md, docs/docs/how-formality-works/closer-look-ty.md, src/decl/decl-to-clause.rkt, src/decl/grammar.rkt, src/ty/grammar.rkt, src/ty/test/test-alias-subtyping.rkt, src/ty/test/test-outlives.rkt, src/ty/test/test-subtyping.rkt
Some additional cleanup after #18.
* Fixed `TyVar` -> `type` and `TyApply` -> `rigid-ty` in documentation
* some remaining uses in blog/2022-50-12.mdx but I left it alone since it looks like a historical document
* Renamed `TyUnit` -> `unit-ty`, because even though it is a term definition rather than a primitive terminal constant, it is closer to a constant than a variable (and this also matches the use of other similar metafunctions like `(vec T)`). I thought about removing the `-ty`, but I think this is a non-context-sensitive macro expansion and I wouldn't want other uses of `unit` outside the type grammar to get expanded.
* Some trailing whitespace and missing final newline issues were auto-fixed by my vscode config in the files I touched. I can disable this behavior or roll it back …
=> some more terminal naming fixes

src/mir/grammar.rkt, src/mir/projection.rkt
This changes the `Place` grammar to directly include projection operations instead of being a pair of a local and a list of projections, so that e.g. you get things like `(field (* x) i)` instead of  `(x (* (field i)))`. This is both easier to read, as well as (presumably) easier to define judgments over.
For applications that do prefer the list-of-projections form, the `apply-projections` and `unpack-projections` functions are provided to convert back and forth.
=> Make `Place` grammar recursive

src/decl/decl-ok/impl-item.rkt, src/decl/test/fn-in-impl-vs-trait-absolutely-same.rkt, src/decl/test/fn-in-impl-vs-trait-different-arg-type.rkt, src/decl/test/fn-in-impl-vs-trait-too-few-where-clause.rkt, src/decl/test/fn-in-impl-vs-trait-too-many-where-clause.rkt
Very basic check that function declarations in impls vs traits match. Checks:
* impl and trait version of fn have the same generic parameters (this is too strict, compared to rustc, because of late-bound lifetimes)
* parameter types on the trait are a subtype of parameter types on the impl
* return type on the impl is a subtype of return type on the trait
I can't remember precisely how this check compares to rustc! This is the most general version, but I think rustc requires equality perhaps in some places. We should figure that out.
Fixes #69
=> check that fn decls in impls/traits match

src/mir/all-check.rkt, src/mir/grammar-extended.rkt, src/mir/type-check-goal.rkt, src/mir/type-of.rkt, src/mir/well-formed-mir.rkt, src/rust/test/type-check--return-ref-to-local.rkt
This makes the `type-check--return-ref-to-local` test pass.
=> Expand MIR well-formedness rules and implement function input/output goals

src/body/borrow-check.rkt, src/body/borrow-check/initialization-check.rkt, src/body/borrow-check/initialization-infer.rkt, src/body/borrow-check/initialization-update.rkt, src/body/borrow-check/move-set-map.rkt, src/body/borrow-check/move-set.rkt, src/body/borrow-check/places.rkt, src/body/grammar.rkt, src/body/type-of.rkt, src/rust/test/borrowck-initialization--access-uninit-var.rkt
This extends the borrow check to check for initialized and uninitialized variables. The code is "first draft" and rather minimally tested. I should probably push a few more tests before we land it.
Fixes https://github.com/nikomatsakis/a-mir-formality/issues/84
=> initialization check, first draft

src/body/grammar.rkt
The nonterminal `Operands` is used (e.g. in `call`) but was not actually defined in the grammar.
=> Add missing definition of Operands

src/gen.rs, src/lib.rs, src/main.rs, tests/input/issue25860.rkt, tests/test.rs
This allows running `cargo run path/to/input.rs` to translate the given program to racket and evaluate the result. The execution is successful if there is no output on stderr when running racket.
=> Evaluate generated racket programs

racket-src/body/grammar.rkt, racket-src/body/type-check-goal.rkt, racket-src/body/type-of.rkt, racket-src/body/well-formed-mir.rkt, racket-src/decl/grammar.rkt, src/gen.rs, src/gen/consts.rs, src/gen/decl.rs, src/gen/mir.rs, src/gen/ty.rs, src/lib.rs, tests/input/issue25860.rkt
This PR expands the body grammar, adding aggregate and cast rvalue variants as well as supporting more constant values. Besides the racket definitions, the formality generator was adapted as well. As a result, the issue25860 example can now be fully translated. The well-formedness and type checking of the new constructs is not yet fully implemented. Also, I want to add some more tests.
=> Expand body grammar

racket-src/body/type-of.rkt, racket-src/decl/env.rkt, racket-src/decl/grammar.rkt, racket-src/ty/grammar.rkt, racket-src/ty/hook.rkt, racket-src/ty/parameters.rkt, racket-src/ty/test/hook.rkt, src/gen/ty.rs
but we're not really testing it in any useful way.
cc @voidc
=> add a fn-def type and adjust type of fn constants

.github/workflows/ci.yaml, revert-redex-changes
Stopgap workaround. Don't know enough redex to investigate yet, but the tests start failing after this change: https://github.com/racket/redex/commit/3a47c0232593fdddde99ddff6c842f0fb4f347d7
=> Temporarily switch redex back to 8.5

.github/workflows/ci.yaml
This reduces CI run duration from `~17m 43s` to `~8m 8s` with more parallelisms. The downside is that if a new module is added beside `logic, ty, decl, body, check, rust` in the future, ci configuration needs to be updated for its tests to run.
=> Split CI racket tests according to directories.

racket-src/body/type-check-goal.rkt, racket-src/body/type-of.rkt, racket-src/decl/well-formed/parameter.rkt, racket-src/rust/test/type-check-reify.rkt, racket-src/ty/grammar.rkt
This implements a function to get the signature from a function type and uses it to type-check function calls and reification casts in MIR. 
closes #100
closes #101
=> Type-check function calls and reification casts

Cargo.lock, Cargo.toml, tests/test.rs
Just in case it's interesting to you (feel free to close this, if not), this PR adds `pretty-assertions` to use its richer `assert_eq` that diffs large output.
This turns the currently failing test in PR #111 (https://github.com/nikomatsakis/a-mir-formality/actions/runs/3207351408/jobs/5242142623#step:4:85)
from this 
to this
=> Use assertions with richer diff

docs/blog/2022-05-12.mdx, docs/docs/how-formality-works/closer-look-ty.md, docs/docs/what-formality-can-do/case-study.md
The Citeseer links to the two papers have broken; this replaces them with researchgate links.
=> Update links to papers

.github/workflows/ci.yaml, crates/formality-check/src/lib.rs, crates/formality-check/src/where_clauses.rs, crates/formality-macros/src/test.rs, crates/formality-prove/src/prove/prove_wc.rs, crates/formality-prove/src/prove/prove_wf.rs, crates/formality-rust/src/grammar.rs, crates/formality-rust/src/prove.rs, crates/formality-types/src/fold.rs, crates/formality-types/src/grammar.rs, crates/formality-types/src/grammar/consts.rs, crates/formality-types/src/grammar/consts/valtree.rs, crates/formality-types/src/grammar/formulas.rs, crates/formality-types/src/grammar/ty.rs, crates/formality-types/src/grammar/ty/debug_impls.rs, crates/formality-types/src/grammar/ty/parse_impls.rs, crates/formality-types/src/visit.rs, tests/consts.rs, tests/hello_world.rs
In contrast to #127, this PR does not attach types to const generic params, but introduces a `type_of_const` where bound, that constrains that generic const parameter to have a specific type.
At present you can create incoherent where bounds where a single const param ends up having two different types at the same time. I should fix that. This is not really an issue, as rustc will never generate such wrong `type_of_const` bounds.
=> Implement const generics take 2

Cargo.lock, Cargo.toml, crates/formality-smir/Cargo.toml, crates/formality-smir/src/lib.rs, rust-toolchain
This set-up a separate crate for conversions from SMIR types to Mir formality decls.
I think it won't make a lot of sense to unit test this, we can add some ui tests as we add more conversion. I've more stuff on my local repo but I guess we can start discussing the set-up of this idea in a smaller PR. 
r? @nikomatsakis
=> Smir to formality basic set-up

crates/formality-prove/src/decls.rs, crates/formality-prove/src/prove/constraints.rs, crates/formality-prove/src/prove/env.rs, crates/formality-types/src/parse.rs
```
warning: length comparison to one
--> crates/formality-rust/src/grammar.rs:37:12
|
37 |         if traits.len() < 1 {
|            ^^^^^^^^^^^^^^^^ help: using `is_empty` is clearer and more explicit: `traits.is_empty()`
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#len_zero
= note: `#[warn(clippy::len_zero)]` on by default
```
=> Replace length comparison to zero by `is_empty()` method

Cargo.lock, Cargo.toml, crates/formality-core/Cargo.toml, crates/formality-core/README.md, crates/formality-macros/Cargo.toml, crates/formality-macros/READE.md, crates/formality-macros/src/cast.rs, crates/formality-macros/src/debug.rs, crates/formality-macros/src/parse.rs, crates/formality-macros/src/term.rs, src/main.rs, tests/associated_type_normalization.rs, tests/coherence_overlap.rs, tests/projection.rs, tests/ui.rs
Changes needed to publish formality-macros and formality-core to crates.io (done!). I want to be able to experiment with these for other languages. Eventually I'd like to publish all of a-mir-formality, just because.
I made the types team owners of these crates, but are there other owners I should add? I expect so, I didn't see obvious docs on forge.
=> Publish formality core

crates/formality-check/src/impls.rs, crates/formality-prove/src/decls.rs
This PR contains the few improvements discussed in review of #128 (but has already been merged, hence this new PR):
- I initially customized `Safety`'s `Debug` impl to special-case the default value and print nothing. That was unnecessary after the recent parser changes and the pretty-printing fix cherry-picked in that PR: it ended up being similar to the default derived `Debug`  impl for `#[term]`s, and can be removed.
- re-introduces the struct pattern in `check_trait_impl` for better errors if the struct is modified.
- introduces the same pattern for `check_neg_trait_impl` for the same reason.
=> Improvements to unsafe trait support

.github/workflows/ci.yaml, rust-toolchain, src/test/coherence_orphan.rs, src/test/consts.rs, src/test/decl_safety.rs, src/test/functions.rs, src/test/mod.rs, tests/judgment-error-reporting/cyclic_judgment.rs
This PR adds a `rustfmt` step to CI, and reformats everything to make it pass.
Fixes #170
I've also removed some default rustup components, as they are currently unused and slow down CI and local toolchain installs, e.g. unpacking all the documentation. 
(This also updates a CI action triggering [deprecation warnings](https://github.com/rust-lang/a-mir-formality/actions/runs/9077579003?pr=172), but [the other one](https://github.com/actions-rs/cargo) the repo uses is also deprecated and [triggers warnings](https://github.com/rust-lang/a-mir-formality/actions/runs/9078065678)).
=> Add rustfmt check to CI

crates/formality-check/src/impls.rs, crates/formality-core/src/cast.rs, crates/formality-core/src/collections.rs, crates/formality-core/src/judgment/proven_set.rs, crates/formality-core/src/parse.rs, crates/formality-core/src/parse/parser.rs, crates/formality-core/src/parse/parser/left_recursion.rs, crates/formality-macros/src/attrs.rs, crates/formality-macros/src/constructors.rs, crates/formality-macros/src/fold.rs, crates/formality-macros/src/parse.rs, crates/formality-macros/src/precedence.rs, crates/formality-macros/src/spec.rs, crates/formality-types/src/grammar/ty.rs, crates/formality-types/src/grammar/ty/debug_impls.rs, crates/formality-types/src/grammar/ty/parse_impls.rs
When adding rustfmt to CI, I noticed clippy was installed by default so I tried it and heard its many complaints with aplomb. (It hates the macro parsing in particular). 
This PR cuts down on the number of warnings it generated, in different commits so they can be dropped in case some of its suggestions are suboptimal.
=> Some clippy fixes

crates/formality-prove/src/decls.rs, crates/formality-prove/src/prove/prove_via.rs, crates/formality-prove/src/prove/prove_wc.rs, crates/formality-rust/src/prove.rs, crates/formality-types/src/grammar/formulas.rs, crates/formality-types/src/grammar/wc.rs
This change inlines the `PR` enum variants into the `WcData` enum. The comment on `PR` "we need to come up with a better name for this" indicates this type is not encoding some deeper logical idea. This change passing all tests indicates that the type is also not necessary.
=> inline PR into WcData

crates/formality-check/src/where_clauses.rs, crates/formality-rust/src/grammar.rs, src/test/consts.rs, src/test/mod.rs
This change is mostly motivated by a comment on `prove_where_clause_well_formed`:
> FIXME(oli-obk): figure out why is this a function and not a `judgment_fn`.
I originally started with converting it to a `judgement_fn` but found I was duplicating a lot of logic from `prove_wc` which already exists. So I settled on moving the logic to a `WhereClause::well_formed` method which creates a set of goals to prove, and then calls `prove_wc` on those goals. 
I'm not _certain_ this is an improvement on the current code. There is more code being run (constructing a set of goals, then checking them is more than just checking), so I wouldn't expect any performance improvement, and it sort of looks like the same code just in a different place, so it's not removing much. The only justification I have is …
=> replace custom wf check with well_formed constructor 

crates/formality-check/src/traits.rs, src/test/mod.rs
This PR adds checks for duplicate function names or duplicate associated type names.
=> Check trait items for duplicate function names or associated type names

crates/formality-rust/src/test.rs
- Update import.
- Update expected debug output.
- Remove inaccurate comments.
=> Reinstate test cases for parsing

crates/formality-prove/src/prove.rs, crates/formality-prove/src/prove/is_local.rs, crates/formality-prove/src/prove/prove_after.rs, crates/formality-prove/src/prove/prove_eq.rs, crates/formality-prove/src/prove/prove_normalize.rs, crates/formality-prove/src/prove/prove_via.rs, crates/formality-prove/src/prove/prove_wc.rs, crates/formality-prove/src/prove/prove_wc_list.rs, crates/formality-prove/src/prove/prove_wf.rs, crates/formality-prove/src/test/adt_wf.rs, crates/formality-prove/src/test/eq_assumptions.rs, crates/formality-prove/src/test/eq_partial_eq.rs, crates/formality-prove/src/test/is_local.rs, crates/formality-prove/src/test/magic_copy.rs, crates/formality-prove/src/test/occurs_check.rs, crates/formality-prove/src/test/universes.rs, src/test/coherence_orphan.rs, src/test/consts.rs, src/test/functions.rs, src/test/mod.rs
Decls debug rendering is a bit noisy, especially since decls does not
change, but is printed for every step that failed.  With this change,
decls is only printed in the `prove` judgement, with the expectation that
this is the main entrypoint for proofs.
=> reduce decls Debug noise

crates/formality-prove/src/prove/prove_wc.rs, crates/formality-prove/src/prove/prove_wf.rs, src/test/mod.rs, src/test/well_formed_trait_ref.rs
Closes #189
Also adds a rule to `prove_wf()` saying that the `'static` lifetime counts as well-formed.
=> When proving WellFormedTraitRef, require the parameters to be well-formed

crates/formality-core/src/judgment.rs
Currently, the names of the matched rules are displayed in certain paths, prominently when there is an error or constraints are produced. This PR displays the names of the rules whenever a rule is matched. The benefit is that the rules picked are easily identified when debugging, even when the test case does not expect a failure. From experience, I find it particularly helpful for beginners to this project.
=> Display matched rules in more proof paths

crates/formality-prove/src/prove/prove_via.rs, crates/formality-types/src/grammar/wc.rs
Split some useful comments added by @nikomatsakis  from my branch.
=> Add comments

crates/formality-check/src/fns.rs, crates/formality-check/src/impls.rs, crates/formality-check/src/lib.rs, crates/formality-check/src/mini_rust_check.rs, crates/formality-check/src/traits.rs, crates/formality-core/src/cast.rs, crates/formality-core/src/fold.rs, crates/formality-core/src/parse.rs, crates/formality-core/src/visit.rs, crates/formality-prove/src/prove/prove_wc.rs, crates/formality-rust/src/grammar/minirust.rs, src/lib.rs, src/test/mir_fn_bodies.rs, src/test/mod.rs
This PR added some basic type checking for mir fn bodies.
=> Typeck mir fn bodies
